### ISSUE TITLE
Exercise?

### ISSUE THREAD

**Issue by Finii** [ignamartinoli/blankspace#1]
Maybe this is an exercise, and I do not want to criticize, just wanted to make sure that you know, that `vim` / `neovim` do this out of the box? I'm not sure about `elvis` or the real `vi`, both I used literally decades ago.

I have something like this in my `nvim/init.vim`:
```
set list
set listchars=tab:»\ ,trail:•,extends:»,precedes:«
```
But you can go fancy there.

`trail` is 'trailing whitespace', `eol` would be end of line (you mention something like that in the readme).

Do `:help listchars` in neovim...

Please just close after you read this :-)

**Comment by ignamartinoli** [comment]
Thanks @Finii ahaha, yes I had that same line in my `init.vim` :smile:

I want to be more involved in the FOSS community, so I began learning about **Git** and **Neovim** plugin development by creating this small project around that feature.

You're my first GitHub Issue ever ahahah :)
